# Pandas Practice

### Import Library

In [1]:
import pandas as pd

### Load Data/Read Data Which you Work

In [2]:
df = pd.read_csv('Pokemon.csv')
df.head(2)

,Id,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

### 1. Check Datatype our Data

In [ ]:
type(df)   # Give Datatype of our Data

### 2. See all columns in our Data

In [ ]:
df.columns    # Give all Columns in our Data

### 3. Extract      'Only One' column is called series

In [ ]:
df['Name']

# if you can check dataype df['id'] - Output is "Series"

### 4. Extract  'More Than One' column is called Dataframe

In [ ]:
df[['Id','Name','Legendary']]  # Pass more than one column name in the list

# if you can check dataype df[['id','season','city']] - Output is "Dataframe"

###  5. Check "Information" of our Data

In [ ]:
df.info()  # Give information of our complete Data

### 6. Check "Statistical Summary (One Line Summary)" of our Data

In [ ]:
df.describe()   #Give Statics Summary of our Data (working on Numerical Data)

### 7. Extract "Only Upper" rows of our Data

In [ ]:
df.head(2)  # Give 3 upper rows of our Data

### 8. Extract  "Only Bottom"  rows of our Data

In [ ]:
df.tail(2)  # Give 2 bottom rows of our Data

### 9. Get the Data Types all the Columns

In [ ]:
df.dtypes

###  10. Get the Data Type of Particular Column

In [ ]:
df['Legendary'].dtypes

### 11. Get the Shape our Data

In [ ]:
df.shape    # (rows, column)

### 12. If Metadata(Column Name) did not our data then What i do?

In [ ]:
# import pandas as pd 
# column_name = ['id', 'name', 'city', 'email']        # First you can create the list and give column name 
# df = pd.read_csv('file_path or file name', names = column_name)     # Then pass 'names' attribute inside the read_csv method
# # df

### 13. If Your file sapareted any symbol like @

In [ ]:
# df = pd.read_csv('file path', delimeter = '@')  # You pass attribute 'delimeter' inside the read_csv method
# df                                              # You can also pass attribute 'sep' inside the read_csv method both are same

### 14. Create a New Column in our data

In [ ]:
df['new_column'] = df['Sp. Atk'] - df['Attack']     # which you create new column in your data added in a last
df.head(5)

### 15.  'Filtering'  by Behalf of Slicing & Index Using ' ILOC(INDEX LOCATION) '  FUNCTION

In [ ]:
df.iloc[2:5, 1:4]   # Get 2,3,4,5 rows and 2,3,4 columns

### 16.  'Filtering'  by Behalf of Data Using  ' LOC(LOCATION) ' FUNCTION

In [ ]:
# -------Find Attack is 100
a = df.loc[df['Attack']==100]  
a 

# -------Find where Name is Venusaur
b = df.loc[df['Name']=="Venusaur"]
# b

# Multiple Flitering by diffrent Condition-------------

#--------Find where is Name is Venusaur AND Type 1 is Grass   
c = df.loc[ (df['Name']=='Venusaur') & (df['Type 1']=='Grass') ]            # For AND condition use & sign
# c

#--------Find where is Name is Venusaur OR Type 1 is Grass  
d = df.loc[ (df['Name']=='Venusaur') | (df['Type 1']=='Grass') ]            # For OR condition use | sign
# d

# For show Columns which you want during flitering
e = df.loc[ (df['Name']=='Venusaur') & (df['Type 1']=='Grass') ][['Name','Type 1']]   # First you filter then   
# e                                                                                 # In last gives columns name given list

### 17. ' ISIN ' Function

In [ ]:
# isin function same as IN keyword

data_in_rows = ['Grass','Fire', 'Rock']
data = df.loc[df['Type 1'].isin(data_in_rows)]
data.head(2)

### 18. Check Total no. of Non Null Values All Column Using ' COUNT ' function - Valid on Single Col and DataFrame

In [ ]:
df.count()                  # Apply Whole DataFrame 
# df['Name'].count()        # Apply Single Col Only

### 19.  Value Counts in Columns using ' VALUE_COUNTS ' function

In [ ]:
df['Type 1'].value_counts()
# df.value_counts()

### 20. Sort Values(ASC or DSC) in Data Using ' SORT_VALUES ' function

In [ ]:
# By default order in Ascending if you sorting want desending then pass attribute ascending = False

# Sorting according Desending Order 
df.sort_values('Type 1')

# Sorting in Multiple Columns given columns names inlist  

# And we want city in ascending order and win_by_runs in Decending order
df.sort_values(['Type 1','Type 2'], ascending = [True, False]).head(5)

### 21.1 Check Total No. of Unique values All Columns in Data Using  ' NUNIQUE ' function - Valid on Whole              Dataframe and particular Column

In [ ]:
df.nunique()                     # Use Whole DataFrame
# df['Name'].nunique()           # Use Particular Column

### 21.2  Show Unique Values in our Data using ' UNIQUE ' function -  Valid On Single Column

In [ ]:
df['Type 1'].unique()

### 23. Group By Function

In [ ]:
# Group by is apply on Catagorical Columns

# For apply one column with agg function
df.groupby('HP').sum()

# For apply Multiple column with agg function
# df.groupby(['HP', 'Speed']).sum()

# With multiple aggregate using agg() function
# df.groupby(['HP', 'Speed']).agg(['count','sum','min'])

# Also you can filter and apply operation

### 23.1 Check Null Values in our All Columns in Data

In [4]:
df.isnull().sum()

Id              0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

### 23.2 Check Null Values in our Data for Particular Column

In [3]:
df['Type 2'].isnull().sum()

386

### 23.3 Check Total Null Values in our Data

In [14]:
df.isnull().sum().sum()

386

### 23.4 ISNA()  Function

In [13]:
df.isna().sum()

Id              0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

### 23.5 NOTNA() Function

In [18]:
df.notna().sum()

Id            800
Name          800
Type 1        800
Type 2        414
Total         800
HP            800
Attack        800
Defense       800
Sp. Atk       800
Sp. Def       800
Speed         800
Generation    800
Legendary     800
dtype: int64

### 24. Check Total No. of Indexes

In [ ]:
df.index

### Rearange of the columns in our Data using df.reindex()

In [ ]:
# df = df.reindex(columns=['movie_title','genre', 'mpaa_rating','inflation_adjusted_gross','total_gross','release_date'])
# df

### 25.1 Check Largest Value in Numerical Column Using ' NLARGEST ' function

In [ ]:
# if you want top 8 largest value then pass df['Speed'].nlargest(8)
df['Speed'].nlargest()


# Apply nlargest method in Whole DataFrame with column name
df.nlargest(5,'Speed')

### 25.2 Chek Smallest Value in Numerical Column Using ' NSMALLEST ' function

In [ ]:
# if you want top 8 smallest value then pass df['Speed'].nsamllest(8)
df['Speed'].nsmallest()   


# Apply nlargest method in Whole DataFrame with column name
df.nsmallest(5,'Speed')

### 26.1 Sum Function ' SUM() '

In [ ]:
df.sum()             # if you want row wise sum pass attriute axis = 1
                     # if you want columns wise sum pass attriute axis = 0 ( by default)
    
    
# For Particularly Column wise sum   
df['Speed'].sum()

### 26.2 Mean Function ' Mean() '

In [ ]:
df.mean()                # if you want row wise mean pass attriute axis = 1
                         # if you want columns wise mean pass attriute axis = 0 ( by default)

### 26.3 Standard Deviation Function  ' STD() '

In [ ]:
df.std()                        # if you want row wise std pass attriute axis = 1
                         # if you want columns wise std pass attriute axis = 0 ( by default)

### 26.4 Varience Function ' VAR() '

In [ ]:
df.var()                        # if you want row wise var pass attriute axis = 1
                         # if you want columns wise var pass attriute axis = 0 ( by default)

### 26.5 Median Function ' MEAN() '

In [ ]:
df.mean()                        # if you want row wise mean pass attriute axis = 1
                         # if you want columns wise mean pass attriute axis = 0 ( by default)

### 27.1  Set Index from a Column using ' SET_INDEX( ) ' Function

In [ ]:
data = df.set_index('Name')
data

### 27.2 Reset Index using ' RESET_INDEX() ' Function

In [ ]:
data.reset_index()

### 27.3 Sort Index Using ' SORT_INDEX() ' function

In [ ]:
# If your index is not sequence wise then apply sort_index() method

df.sort_index()

### 28. Drop(Delete)  Any Column using ' Drop() ' Function

In [ ]:
drop_col = df.drop(columns = 'Name')       # If you Drop multiple columns then pass columns names list
drop_col

### 29.1 All Rows Show in Data using ' PD.SET_OPTION() '

In [ ]:
pd.set_option('display.max_rows',1000)

### 29.2 All Columns Show in our Data ' PD.SET_OPTION() '

In [ ]:
pd.set_option('display.max_columns',13)

### 29.3 Default Rows/Columns in DataFrame Using ' PD.RESET_OPTION()  '

In [ ]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

### 30. Create own Function

In [ ]:
# We Create Function When i don't have any logic or any method then we create function and calling by apply method in Series


# Q. Create a Column where if id%2 ==0 then Even else False
def even_odd(x):
    if x%2==0:
        return 'Even'
    return False

df['id_in_even_odd'] = df['Id'].apply(even_odd)


# Q. Create a Column where Speed in Miles from Kilometers 
def miles(x):
    return x*0.62137

df['speed_in_miles'] = df['Speed'].apply(miles)


# Q. Create a Column where Generation in int to alphabet
def int_to_alpha(y):
    if y == 1:
        return 'One'
    elif y == 2:
        return 'Two'
    elif y == 3:
        return 'Three'
    elif y == 4:
        return 'Four'
    elif y == 5:
        return 'Five'
    else:
        return 'Six'
    
df['gen_to_alphabet'] = df['Generation'].apply(int_to_alpha)

### 31. Concat Files

In [ ]:
df1 = pd.read_csv('file_path1')
df2 = pd.read_csv('file_path2')
df = pd.concat([df1,df2])

### 32. Merge Files

In [ ]:
df1 = pd.read_csv('file_path1')
df2 = pd.read_csv('file_path2')

df = df1.merge(df2, on = 'id', how = 'outer')     # here on is primary key common column in your dataframe give here
                                                  # here how parametr is a inner/left/right choose bases of you condition

    
# if your common column name is diff but work as same like id = eid
# Then you pass attribute left_on and right_on
df = df1.merge(df2, on = 'id', left_on = 'id', right_on = 'eid') 


# If You merge a lot of files then you Use for loop - 
df1 = pd.read_csv('file_path1')
df2 = pd.read_csv('file_path2')
df3 = pd.read_csv('file_path3')
df4 = pd.read_csv('file_path4')

df = df1
dfs = [df2,df3,df4]

for i in dfs:
    df = df.merge(i, on = 'id')

df

### 33. Pivot Table 
Pivot tables are another way of calculating grouped summary statistics. Pivot Table is similiar to Groupby Basically pivot tables are used in spreadsheets, if you have ever used spreadsheets then chances are you have used pivot tables. Let's see how to create pivot tables in pandas.

In [ ]:
walmart = pd.read_csv('walmart.csv')
walmart.drop(columns = 'Unnamed: 9', inplace = True)

In [ ]:
walmart.head(3)

In [ ]:
# Pivoting for mean Weekly_Sales for each store Type
walmart.pivot_table(index = ["Type"], values = "Weekly_Sales")       # By Default Pivot give Mean

# Pivoting for max Weekly_Sales for each store Type using pass aggfunc
walmart.pivot_table(index = ["Type"], values = "Weekly_Sales", aggfunc = max)

# Pivoting for max, min Weekly_Sales for each store Type using pass aggfunc
walmart.pivot_table(index = ["Type"], values = "Weekly_Sales", aggfunc = [max, min])

# Pivoting for mean Seekly_Sales by store Type and Holiday 
walmart.pivot_table(index = "Type", columns = 'Is_Holiday', values = "Weekly_Sales")

# Printing mean of Weekly_Sales by Department and Type
walmart.pivot_table(index = 'Department', columns = 'Type', values = 'Weekly_Sales')

# Printing mean of Weekly_Sales by Department and Type, fill missing values with 0
walmart.pivot_table(values='Weekly_Sales', index='Department', columns='Type', fill_value=0)

# Printing the of mean Weekly_Sales by Department and Type, sum all rows and cols
walmart.pivot_table(values = "Weekly_Sales", index = "Department", columns = "Type", margins = True)

### 34. Drop Duplicates

In [ ]:
# Give single Column name where you drop duplicates
df.drop_duplicates(subset = 'Type 1')

In [ ]:
# Give Column name in the list where you drop duplicates
df.drop_duplicates(subset = ['Type 1', 'Speed'])

### 35. Insert Create Column In Specific Location in Your DataFrame

In [ ]:
# df['all_type'] = df['Type 1'] + " " + df['Type 2']
# df.insert(4,'All_Type',df['all_type'])
# df

In [ ]:
df

# 36. Handling Missing Values 

To work with Missing Values you have a two way for Handle Missing Values
 - 1 -    To Drop Using Dropna()  
 
 
 - 2 -    To Fill Using Fillna()

### 36.1 Drop NAN Values Using Dropna() 

Syntax - df.dropna(axis, how, thresh, subset, inplace)
 
   - axis{0 or 'rows', 1 or ‘columns’}, By default 0 
   
    -------0, or ‘rows’ : Drop rows which contain missing values.

    -------1, or ‘columns’ : Drop columns which contain missing value.
    
   
   - how: {‘any’, ‘all’}, By default ‘any’
   
    -------if row or column is removed from DataFrame, when we have at least one NA or all NA.

    -------‘any’ : If any NA values are present, drop that row or column.

    -------‘all’ : If all values are NA, drop that row or column.
    
   
   - thresh: thresh takes integer value which tells minimum amount of na values to drop.
   
   - subset: It’s an array which limits the dropping process to passed rows/columns through list.
   
   - inplace: It is a boolean which makes the changes in data frame itself if True.

In [ ]:
miss = pd.read_csv('miss.csv')
miss

In [ ]:
miss.isnull().sum()   # No. of Null Values in Every Columns
miss.isnull().sum().sum()   # Total Null Values

In [ ]:
miss.dropna()             # All data deleted where NAN vlaues Exist
#or
miss.dropna(axis = 0)     # # Which rows deleted have a NAN values

In [ ]:
# Which Columns deleted have a NAN values
miss.dropna(axis = 1)

In [ ]:
# Which Row deleted Where have a Nan Values. by default how = 'any'
miss.dropna(how = 'any')

In [ ]:
# Deleted Row Where completely All NAN values Exist 
miss.dropna(how='all')

In [ ]:
# We use Thresh parameter when we want a specific not null values Given a int number
# Drop NAN vlaues where at least 2 Not Null Values
miss.dropna(thresh=2) # By default axis = 0

In [ ]:
# single given Column name in the list where city have NAN values will be deleted
# Subset Parameter is optional
miss.dropna(subset=['city'])

In [ ]:
# Multiple given Column name in the list where city and state have NAN values will be deleted
# Subset Parameter is optional
miss.dropna(subset=['city','state'])

### 36.2 Fill NAN Values Using Fillna() 
syntax - fillna(value, method, axis, inplace, limit, downcast)
 - Value - Number, String, Dictionary, Series, DataFrame 
         Required, Specifies the value to replace the NULL values with.This can also be values for the entire row or column
         
 - Method - {‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None
         Method is used if user doesn’t pass any value. Pandas has different methods like bfill, backfill or ffill forward fill which fills the place with value in the Forward index or Previous/Back respectively.
         
 - Axis - {0 or ‘index’, 1 or ‘columns’}
 
        Optional, default 0. The axis to fill the NULL values along
        
 - Limit - int, default None
 
         Optional, default None. Specifies the maximum number of NULL values to fill (if method is specified)
        
 - Downcast - dict, default is None
 
        It takes a dict which specifies what dtype to downcast to which one. Like Float64 to int64.

In [ ]:
# All NAN values replace by 0
miss.fillna(0)

# All NAN values replace by none
miss.fillna('none')

In [ ]:
# Fill NAN values specific Column wise
miss.fillna({'fname': 'none', 'lname':'Null', 'age': 21}).info()

In [ ]:
# Fill NAN values by bfill (Backwardfill)
miss.fillna(method = 'bfill')

# Fill NAN values by ffill (Forwardfill)
miss.fillna(method = 'ffill')

# Fill NAN values by pad 
miss.fillna(method = 'pad')

# Fill NAN values by backfill
miss.fillna(method = 'backfill')

In [ ]:
# Fill NAN values by Axis(row wise) using method or values
miss.fillna(method = 'ffill', axis = 0)

# Fill NAN values by Axis(column wise) using method or values
miss.fillna(method = 'ffill', axis = 1)

In [ ]:
# Fill NAN values but specific NAN values by Limit using method or value
miss.fillna(limit = 2 ,value = 0)

In [ ]:
# Fill NAN value in single column
miss['age'] = miss['age'].fillna(0)
miss

In [ ]:
# Fill NAN value in Multiple column
miss[['age', 'city']] = miss[['age', 'city']].fillna(method = 'bfill')
miss

# 37. Date Time

In [22]:
# Parse_Dates paramaeter inside the read_csv method and convert Date Column datatype automatically - parse_dates = ['col_name']
# or 
# df['col_name'] = pd.to_datetime(df['col_name'])

tsd = pd.read_csv('walmart.csv')
tsd.head(2)

,Store,Type,Department,Weekly_Sales,Is_Holiday,Temperature,Fuel_Price,Unemployment,Date
0,1,A,1,57258.43,False,62.27,2.719,7.808,14-02-2010
1,1,A,1,16333.14,False,80.91,2.669,7.787,07-03-2010

In [18]:
# Check Date Column data type and convert into date time data type
tsd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282451 entries, 0 to 282450
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         282451 non-null  int64
 1   Type          282451 non-null  object
 2   Department    282451 non-null  int64
 3   Weekly_Sales  282451 non-null  float64
 4   Is_Holiday    282451 non-null  bool
 5   Temperature   282451 non-null  float64
 6   Fuel_Price    282451 non-null  float64
 7   Unemployment  282451 non-null  float64
 8   Date          282451 non-null  object
dtypes: bool(1), float64(4), int64(2), object(2)
memory usage: 17.5+ MB

In [25]:
tsd['Date'] =  pd.to_datetime(tsd['Date'], format = "%d-%m-%Y")
tsd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282451 entries, 0 to 282450
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         282451 non-null  int64
 1   Type          282451 non-null  object
 2   Department    282451 non-null  int64
 3   Weekly_Sales  282451 non-null  float64
 4   Is_Holiday    282451 non-null  bool
 5   Temperature   282451 non-null  float64
 6   Fuel_Price    282451 non-null  float64
 7   Unemployment  282451 non-null  float64
 8   Date          282451 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 17.5+ MB

### 38. Pandas Profiling

In [23]:
# pip install pandas-profiling
from pandas_profiling import ProfileReport
# df.profile_report()

### 39. DataFrame Intractive Visualization

In [20]:
# !pip install dtale
import dtale

In [24]:
# dtale.show(df)

### 40. Outliers